name: Deploy-S3-and-Artifact
on: [push]

jobs:
  create-s3:
    runs-on: ubuntu-latest
    steps:
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1  # Change region if needed

      - name: Create S3 Bucket
        run: |
          BUCKET_NAME="my-unique-bucket-$RANDOM" && aws s3api create-bucket --bucket "$BUCKET_NAME" --region us-east-1 && echo "S3 Bucket Created: $BUCKET_NAME"

  upload-artifact:
    runs-on: ubuntu-latest
    steps:
      - name: Run a one-line script
        run: echo 'The S3 has been deployed successfully check this cmd in CLI:aws s3api list-buckets --query "Buckets[].{Name:Name}" --output table' > result.txt 

      - name: Upload the result
        uses: actions/upload-artifact@v4.6.2
        with:
          name: Output-file 
          path: result.txt
