name: Artifacts
on: [push]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Run a one-line script
        run: echo "The artifact YAML script has been deployed successfully" > sample-artifact.txt 

      - name: Upload the result
        uses: actions/upload-artifact@v3
        with:
          name: Output-file 
          path: sample-artifact.txt
