name: Deploy-S3-and-Artifact
on: [push]

jobs:
  create-s3:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1  # Change if needed

      - name: Create S3 Bucket
        id: s3_creation
        run: BUCKET_NAME="my-unique-4bucket-$RANDOM" && echo "Creating S3 bucket:$BUCKET_NAME" && if aws s3api create-bucket --bucket "$BUCKET_NAME" --region us-east-1; then echo "S3_BUCKET_NAME=$BUCKET_NAME" >> $GITHUB_ENV && echo "status=success" >> $GITHUB_ENV;  else  echo "status=failure" >> $GITHUB_ENV;  fi

  upload-artifact:
    runs-on: ubuntu-latest
    needs: create-s3  # This job runs only if create-s3 is successful
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Create Artifact with S3 Status
        run: |
          if [[ "${{ env.status }}" == "success" ]]; then
            echo "S3 bucket created successfully. Use the below command to check bucket status in AWS CLI:" > s3-status.txt
            echo "==================================================" >> s3-status.txt
            echo 'Command: BUCKETS=$(aws s3api list-buckets --query "Buckets[].Name" --output text 2>/dev/null); if [ -z "$BUCKETS" ]; then echo "No S3 buckets exist"; else echo "Existing S3 Buckets:"; echo "$BUCKETS"; fi' >> s3-status.txt
          else
            echo "Failed to create S3 bucket" > s3-status.txt
          fi

      - name: Upload S3 Creation Status
        uses: actions/upload-artifact@v4.6.2
        with:
          name: RESULT-S3-Creation-Status
          path: s3-status.txt
