name: Stop-and-Terminate-EC2-Instance
on: [push]

jobs:
  stop-instance:
    runs-on: ubuntu-latest
    steps:
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1

      - name: Stop EC2 Instance
        run: aws ec2 stop-instances --instance-ids i-01f8619dbbb830e26

  terminate-instance:
    needs: stop-instance  # Ensures this runs only after 'stop-instance' job
    runs-on: ubuntu-latest
    steps:
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1

      - name: Terminate EC2 Instance
        run: aws ec2 terminate-instances --instance-ids i-01f8619dbbb830e26
